services:
  db:
    image: postgres:13
    container_name: pismo-postgres
    environment:
      POSTGRES_USER: pismo-user
      POSTGRES_PASSWORD: pismo-secret
      POSTGRES_DB: pismo
      POSTGRES_EXTENSIONS: uuid-ossp
#    volumes: (commenting as schema won't be present during app start up)
#      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pismo-user -d pismo" ]
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:13
    container_name: pismo-postgres-test
    environment:
      POSTGRES_USER: pismo-user-test
      POSTGRES_PASSWORD: pismo-secret-test
      POSTGRES_DB: pismo-test
      POSTGRES_EXTENSIONS: uuid-ossp
#    volumes:
#      - db_data_test:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pismo-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: pismo-user
      DB_PASSWORD: pismo-secret
      DB_NAME: pismo
      STORAGE_TYPE: postgres
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


volumes:
  db_data:
    driver: local
  db_data_test:
    driver: local

