name: Lint

on: 
  push:  # Runs on every push to any branch
    branches:
      - '**'  # Matches all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21 # specify the Go version

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: latest # optional, you can specify a version here
          args: "--timeout 5m" # optional, add any specific golangci-lint arguments

